// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: api/proto/sentinelmesh.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Resources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           string                 `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        string                 `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Gpu           int32                  `protobuf:"varint,3,opt,name=gpu,proto3" json:"gpu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resources) Reset() {
	*x = Resources{}
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinelmesh_proto_rawDescGZIP(), []int{0}
}

func (x *Resources) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *Resources) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *Resources) GetGpu() int32 {
	if x != nil {
		return x.Gpu
	}
	return 0
}

type CheckpointPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Interval      string                 `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointPolicy) Reset() {
	*x = CheckpointPolicy{}
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointPolicy) ProtoMessage() {}

func (x *CheckpointPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointPolicy.ProtoReflect.Descriptor instead.
func (*CheckpointPolicy) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinelmesh_proto_rawDescGZIP(), []int{1}
}

func (x *CheckpointPolicy) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CheckpointPolicy) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

type SecurityPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityPolicy) Reset() {
	*x = SecurityPolicy{}
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityPolicy) ProtoMessage() {}

func (x *SecurityPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityPolicy.ProtoReflect.Descriptor instead.
func (*SecurityPolicy) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinelmesh_proto_rawDescGZIP(), []int{2}
}

func (x *SecurityPolicy) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

type NetworkPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPolicy) Reset() {
	*x = NetworkPolicy{}
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicy) ProtoMessage() {}

func (x *NetworkPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicy.ProtoReflect.Descriptor instead.
func (*NetworkPolicy) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinelmesh_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkPolicy) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type VerificationPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificationPolicy) Reset() {
	*x = VerificationPolicy{}
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationPolicy) ProtoMessage() {}

func (x *VerificationPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationPolicy.ProtoReflect.Descriptor instead.
func (*VerificationPolicy) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinelmesh_proto_rawDescGZIP(), []int{4}
}

func (x *VerificationPolicy) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type Agent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tenant             string                 `protobuf:"bytes,3,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Version            string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Image              string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Resources          *Resources             `protobuf:"bytes,6,opt,name=resources,proto3" json:"resources,omitempty"`
	Priority           string                 `protobuf:"bytes,7,opt,name=priority,proto3" json:"priority,omitempty"`
	SecurityPolicy     *SecurityPolicy        `protobuf:"bytes,8,opt,name=security_policy,json=securityPolicy,proto3" json:"security_policy,omitempty"`
	NetworkPolicy      *NetworkPolicy         `protobuf:"bytes,9,opt,name=network_policy,json=networkPolicy,proto3" json:"network_policy,omitempty"`
	CheckpointPolicy   *CheckpointPolicy      `protobuf:"bytes,10,opt,name=checkpoint_policy,json=checkpointPolicy,proto3" json:"checkpoint_policy,omitempty"`
	VerificationPolicy *VerificationPolicy    `protobuf:"bytes,11,opt,name=verification_policy,json=verificationPolicy,proto3" json:"verification_policy,omitempty"`
	Status             string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinelmesh_proto_rawDescGZIP(), []int{5}
}

func (x *Agent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Agent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Agent) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *Agent) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Agent) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Agent) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Agent) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *Agent) GetSecurityPolicy() *SecurityPolicy {
	if x != nil {
		return x.SecurityPolicy
	}
	return nil
}

func (x *Agent) GetNetworkPolicy() *NetworkPolicy {
	if x != nil {
		return x.NetworkPolicy
	}
	return nil
}

func (x *Agent) GetCheckpointPolicy() *CheckpointPolicy {
	if x != nil {
		return x.CheckpointPolicy
	}
	return nil
}

func (x *Agent) GetVerificationPolicy() *VerificationPolicy {
	if x != nil {
		return x.VerificationPolicy
	}
	return nil
}

func (x *Agent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Agent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Agent) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type AgentRun struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId           string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	State             string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Node              string                 `protobuf:"bytes,4,opt,name=node,proto3" json:"node,omitempty"`
	Cluster           string                 `protobuf:"bytes,5,opt,name=cluster,proto3" json:"cluster,omitempty"`
	StartedAt         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	LastCheckpoint    string                 `protobuf:"bytes,8,opt,name=last_checkpoint,json=lastCheckpoint,proto3" json:"last_checkpoint,omitempty"`
	RetryCount        int32                  `protobuf:"varint,9,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	ResourceUsage     string                 `protobuf:"bytes,10,opt,name=resource_usage,json=resourceUsage,proto3" json:"resource_usage,omitempty"`
	CostEstimate      float64                `protobuf:"fixed64,11,opt,name=cost_estimate,json=costEstimate,proto3" json:"cost_estimate,omitempty"`
	VerificationState string                 `protobuf:"bytes,12,opt,name=verification_state,json=verificationState,proto3" json:"verification_state,omitempty"`
	FailureReason     string                 `protobuf:"bytes,13,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AgentRun) Reset() {
	*x = AgentRun{}
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRun) ProtoMessage() {}

func (x *AgentRun) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRun.ProtoReflect.Descriptor instead.
func (*AgentRun) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinelmesh_proto_rawDescGZIP(), []int{6}
}

func (x *AgentRun) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentRun) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentRun) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AgentRun) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *AgentRun) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *AgentRun) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *AgentRun) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *AgentRun) GetLastCheckpoint() string {
	if x != nil {
		return x.LastCheckpoint
	}
	return ""
}

func (x *AgentRun) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *AgentRun) GetResourceUsage() string {
	if x != nil {
		return x.ResourceUsage
	}
	return ""
}

func (x *AgentRun) GetCostEstimate() float64 {
	if x != nil {
		return x.CostEstimate
	}
	return 0
}

func (x *AgentRun) GetVerificationState() string {
	if x != nil {
		return x.VerificationState
	}
	return ""
}

func (x *AgentRun) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

type Checkpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Version       int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	ArtifactUri   string                 `protobuf:"bytes,5,opt,name=artifact_uri,json=artifactUri,proto3" json:"artifact_uri,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Checksum      string                 `protobuf:"bytes,7,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checkpoint) Reset() {
	*x = Checkpoint{}
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkpoint) ProtoMessage() {}

func (x *Checkpoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkpoint.ProtoReflect.Descriptor instead.
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinelmesh_proto_rawDescGZIP(), []int{7}
}

func (x *Checkpoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Checkpoint) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Checkpoint) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Checkpoint) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Checkpoint) GetArtifactUri() string {
	if x != nil {
		return x.ArtifactUri
	}
	return ""
}

func (x *Checkpoint) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Checkpoint) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type Policy struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tenant          string                 `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	FilesystemRules []string               `protobuf:"bytes,3,rep,name=filesystem_rules,json=filesystemRules,proto3" json:"filesystem_rules,omitempty"`
	NetworkRules    []string               `protobuf:"bytes,4,rep,name=network_rules,json=networkRules,proto3" json:"network_rules,omitempty"`
	ToolRules       []string               `protobuf:"bytes,5,rep,name=tool_rules,json=toolRules,proto3" json:"tool_rules,omitempty"`
	ResourceRules   []string               `protobuf:"bytes,6,rep,name=resource_rules,json=resourceRules,proto3" json:"resource_rules,omitempty"`
	SecretRules     []string               `protobuf:"bytes,7,rep,name=secret_rules,json=secretRules,proto3" json:"secret_rules,omitempty"`
	ApprovalRules   []string               `protobuf:"bytes,8,rep,name=approval_rules,json=approvalRules,proto3" json:"approval_rules,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinelmesh_proto_rawDescGZIP(), []int{8}
}

func (x *Policy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Policy) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *Policy) GetFilesystemRules() []string {
	if x != nil {
		return x.FilesystemRules
	}
	return nil
}

func (x *Policy) GetNetworkRules() []string {
	if x != nil {
		return x.NetworkRules
	}
	return nil
}

func (x *Policy) GetToolRules() []string {
	if x != nil {
		return x.ToolRules
	}
	return nil
}

func (x *Policy) GetResourceRules() []string {
	if x != nil {
		return x.ResourceRules
	}
	return nil
}

func (x *Policy) GetSecretRules() []string {
	if x != nil {
		return x.SecretRules
	}
	return nil
}

func (x *Policy) GetApprovalRules() []string {
	if x != nil {
		return x.ApprovalRules
	}
	return nil
}

type VerificationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Checks        []string               `protobuf:"bytes,2,rep,name=checks,proto3" json:"checks,omitempty"`
	Passed        bool                   `protobuf:"varint,3,opt,name=passed,proto3" json:"passed,omitempty"`
	Failed        []string               `protobuf:"bytes,4,rep,name=failed,proto3" json:"failed,omitempty"`
	Evidence      string                 `protobuf:"bytes,5,opt,name=evidence,proto3" json:"evidence,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificationResult) Reset() {
	*x = VerificationResult{}
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationResult) ProtoMessage() {}

func (x *VerificationResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationResult.ProtoReflect.Descriptor instead.
func (*VerificationResult) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinelmesh_proto_rawDescGZIP(), []int{9}
}

func (x *VerificationResult) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *VerificationResult) GetChecks() []string {
	if x != nil {
		return x.Checks
	}
	return nil
}

func (x *VerificationResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *VerificationResult) GetFailed() []string {
	if x != nil {
		return x.Failed
	}
	return nil
}

func (x *VerificationResult) GetEvidence() string {
	if x != nil {
		return x.Evidence
	}
	return ""
}

func (x *VerificationResult) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type CreateAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Resources     *Resources             `protobuf:"bytes,5,opt,name=resources,proto3" json:"resources,omitempty"`
	Priority      string                 `protobuf:"bytes,6,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAgentRequest) Reset() {
	*x = CreateAgentRequest{}
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentRequest) ProtoMessage() {}

func (x *CreateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentRequest.ProtoReflect.Descriptor instead.
func (*CreateAgentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinelmesh_proto_rawDescGZIP(), []int{10}
}

func (x *CreateAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAgentRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateAgentRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CreateAgentRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateAgentRequest) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *CreateAgentRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

type CreateAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAgentResponse) Reset() {
	*x = CreateAgentResponse{}
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentResponse) ProtoMessage() {}

func (x *CreateAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentResponse.ProtoReflect.Descriptor instead.
func (*CreateAgentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinelmesh_proto_rawDescGZIP(), []int{11}
}

func (x *CreateAgentResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinelmesh_proto_rawDescGZIP(), []int{12}
}

func (x *GetAgentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentResponse.ProtoReflect.Descriptor instead.
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinelmesh_proto_rawDescGZIP(), []int{13}
}

func (x *GetAgentResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinelmesh_proto_rawDescGZIP(), []int{14}
}

func (x *ListAgentsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListAgentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAgentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*Agent               `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinelmesh_proto_rawDescGZIP(), []int{15}
}

func (x *ListAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *ListAgentsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type DeleteAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentRequest) Reset() {
	*x = DeleteAgentRequest{}
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentRequest) ProtoMessage() {}

func (x *DeleteAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAgentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinelmesh_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteAgentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentResponse) Reset() {
	*x = DeleteAgentResponse{}
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentResponse) ProtoMessage() {}

func (x *DeleteAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentResponse.ProtoReflect.Descriptor instead.
func (*DeleteAgentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinelmesh_proto_rawDescGZIP(), []int{17}
}

type CreateRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRunRequest) Reset() {
	*x = CreateRunRequest{}
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRunRequest) ProtoMessage() {}

func (x *CreateRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRunRequest.ProtoReflect.Descriptor instead.
func (*CreateRunRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinelmesh_proto_rawDescGZIP(), []int{18}
}

func (x *CreateRunRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type CreateRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *AgentRun              `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRunResponse) Reset() {
	*x = CreateRunResponse{}
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRunResponse) ProtoMessage() {}

func (x *CreateRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRunResponse.ProtoReflect.Descriptor instead.
func (*CreateRunResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinelmesh_proto_rawDescGZIP(), []int{19}
}

func (x *CreateRunResponse) GetRun() *AgentRun {
	if x != nil {
		return x.Run
	}
	return nil
}

type GetRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunRequest) Reset() {
	*x = GetRunRequest{}
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunRequest) ProtoMessage() {}

func (x *GetRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunRequest.ProtoReflect.Descriptor instead.
func (*GetRunRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinelmesh_proto_rawDescGZIP(), []int{20}
}

func (x *GetRunRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *AgentRun              `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunResponse) Reset() {
	*x = GetRunResponse{}
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunResponse) ProtoMessage() {}

func (x *GetRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunResponse.ProtoReflect.Descriptor instead.
func (*GetRunResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinelmesh_proto_rawDescGZIP(), []int{21}
}

func (x *GetRunResponse) GetRun() *AgentRun {
	if x != nil {
		return x.Run
	}
	return nil
}

type CancelRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRunRequest) Reset() {
	*x = CancelRunRequest{}
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRunRequest) ProtoMessage() {}

func (x *CancelRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRunRequest.ProtoReflect.Descriptor instead.
func (*CancelRunRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinelmesh_proto_rawDescGZIP(), []int{22}
}

func (x *CancelRunRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *AgentRun              `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRunResponse) Reset() {
	*x = CancelRunResponse{}
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRunResponse) ProtoMessage() {}

func (x *CancelRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRunResponse.ProtoReflect.Descriptor instead.
func (*CancelRunResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinelmesh_proto_rawDescGZIP(), []int{23}
}

func (x *CancelRunResponse) GetRun() *AgentRun {
	if x != nil {
		return x.Run
	}
	return nil
}

type GetRunStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunStateRequest) Reset() {
	*x = GetRunStateRequest{}
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunStateRequest) ProtoMessage() {}

func (x *GetRunStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunStateRequest.ProtoReflect.Descriptor instead.
func (*GetRunStateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinelmesh_proto_rawDescGZIP(), []int{24}
}

func (x *GetRunStateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRunStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunStateResponse) Reset() {
	*x = GetRunStateResponse{}
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunStateResponse) ProtoMessage() {}

func (x *GetRunStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sentinelmesh_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunStateResponse.ProtoReflect.Descriptor instead.
func (*GetRunStateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sentinelmesh_proto_rawDescGZIP(), []int{25}
}

func (x *GetRunStateResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

var File_api_proto_sentinelmesh_proto protoreflect.FileDescriptor

const file_api_proto_sentinelmesh_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/sentinelmesh.proto\x12\x0fsentinelmesh.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"G\n" +
	"\tResources\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\tR\x06memory\x12\x10\n" +
	"\x03gpu\x18\x03 \x01(\x05R\x03gpu\"H\n" +
	"\x10CheckpointPolicy\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1a\n" +
	"\binterval\x18\x02 \x01(\tR\binterval\"*\n" +
	"\x0eSecurityPolicy\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\"#\n" +
	"\rNetworkPolicy\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\".\n" +
	"\x12VerificationPolicy\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"\x8e\x05\n" +
	"\x05Agent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06tenant\x18\x03 \x01(\tR\x06tenant\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x128\n" +
	"\tresources\x18\x06 \x01(\v2\x1a.sentinelmesh.v1.ResourcesR\tresources\x12\x1a\n" +
	"\bpriority\x18\a \x01(\tR\bpriority\x12H\n" +
	"\x0fsecurity_policy\x18\b \x01(\v2\x1f.sentinelmesh.v1.SecurityPolicyR\x0esecurityPolicy\x12E\n" +
	"\x0enetwork_policy\x18\t \x01(\v2\x1e.sentinelmesh.v1.NetworkPolicyR\rnetworkPolicy\x12N\n" +
	"\x11checkpoint_policy\x18\n" +
	" \x01(\v2!.sentinelmesh.v1.CheckpointPolicyR\x10checkpointPolicy\x12T\n" +
	"\x13verification_policy\x18\v \x01(\v2#.sentinelmesh.v1.VerificationPolicyR\x12verificationPolicy\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xdd\x03\n" +
	"\bAgentRun\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x12\n" +
	"\x04node\x18\x04 \x01(\tR\x04node\x12\x18\n" +
	"\acluster\x18\x05 \x01(\tR\acluster\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12'\n" +
	"\x0flast_checkpoint\x18\b \x01(\tR\x0elastCheckpoint\x12\x1f\n" +
	"\vretry_count\x18\t \x01(\x05R\n" +
	"retryCount\x12%\n" +
	"\x0eresource_usage\x18\n" +
	" \x01(\tR\rresourceUsage\x12#\n" +
	"\rcost_estimate\x18\v \x01(\x01R\fcostEstimate\x12-\n" +
	"\x12verification_state\x18\f \x01(\tR\x11verificationState\x12%\n" +
	"\x0efailure_reason\x18\r \x01(\tR\rfailureReason\"\xdd\x01\n" +
	"\n" +
	"Checkpoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12!\n" +
	"\fartifact_uri\x18\x05 \x01(\tR\vartifactUri\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1a\n" +
	"\bchecksum\x18\a \x01(\tR\bchecksum\"\x90\x02\n" +
	"\x06Policy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06tenant\x18\x02 \x01(\tR\x06tenant\x12)\n" +
	"\x10filesystem_rules\x18\x03 \x03(\tR\x0ffilesystemRules\x12#\n" +
	"\rnetwork_rules\x18\x04 \x03(\tR\fnetworkRules\x12\x1d\n" +
	"\n" +
	"tool_rules\x18\x05 \x03(\tR\ttoolRules\x12%\n" +
	"\x0eresource_rules\x18\x06 \x03(\tR\rresourceRules\x12!\n" +
	"\fsecret_rules\x18\a \x03(\tR\vsecretRules\x12%\n" +
	"\x0eapproval_rules\x18\b \x03(\tR\rapprovalRules\"\xc9\x01\n" +
	"\x12VerificationResult\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x16\n" +
	"\x06checks\x18\x02 \x03(\tR\x06checks\x12\x16\n" +
	"\x06passed\x18\x03 \x01(\bR\x06passed\x12\x16\n" +
	"\x06failed\x18\x04 \x03(\tR\x06failed\x12\x1a\n" +
	"\bevidence\x18\x05 \x01(\tR\bevidence\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xcb\x01\n" +
	"\x12CreateAgentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x128\n" +
	"\tresources\x18\x05 \x01(\v2\x1a.sentinelmesh.v1.ResourcesR\tresources\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\tR\bpriority\"C\n" +
	"\x13CreateAgentResponse\x12,\n" +
	"\x05agent\x18\x01 \x01(\v2\x16.sentinelmesh.v1.AgentR\x05agent\"!\n" +
	"\x0fGetAgentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x10GetAgentResponse\x12,\n" +
	"\x05agent\x18\x01 \x01(\v2\x16.sentinelmesh.v1.AgentR\x05agent\"l\n" +
	"\x11ListAgentsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"l\n" +
	"\x12ListAgentsResponse\x12.\n" +
	"\x06agents\x18\x01 \x03(\v2\x16.sentinelmesh.v1.AgentR\x06agents\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"$\n" +
	"\x12DeleteAgentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13DeleteAgentResponse\"-\n" +
	"\x10CreateRunRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"@\n" +
	"\x11CreateRunResponse\x12+\n" +
	"\x03run\x18\x01 \x01(\v2\x19.sentinelmesh.v1.AgentRunR\x03run\"\x1f\n" +
	"\rGetRunRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x0eGetRunResponse\x12+\n" +
	"\x03run\x18\x01 \x01(\v2\x19.sentinelmesh.v1.AgentRunR\x03run\"\"\n" +
	"\x10CancelRunRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x11CancelRunResponse\x12+\n" +
	"\x03run\x18\x01 \x01(\v2\x19.sentinelmesh.v1.AgentRunR\x03run\"$\n" +
	"\x12GetRunStateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x13GetRunStateResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state2\xea\x02\n" +
	"\fAgentService\x12X\n" +
	"\vCreateAgent\x12#.sentinelmesh.v1.CreateAgentRequest\x1a$.sentinelmesh.v1.CreateAgentResponse\x12O\n" +
	"\bGetAgent\x12 .sentinelmesh.v1.GetAgentRequest\x1a!.sentinelmesh.v1.GetAgentResponse\x12U\n" +
	"\n" +
	"ListAgents\x12\".sentinelmesh.v1.ListAgentsRequest\x1a#.sentinelmesh.v1.ListAgentsResponse\x12X\n" +
	"\vDeleteAgent\x12#.sentinelmesh.v1.DeleteAgentRequest\x1a$.sentinelmesh.v1.DeleteAgentResponse2\xd9\x02\n" +
	"\n" +
	"RunService\x12R\n" +
	"\tCreateRun\x12!.sentinelmesh.v1.CreateRunRequest\x1a\".sentinelmesh.v1.CreateRunResponse\x12I\n" +
	"\x06GetRun\x12\x1e.sentinelmesh.v1.GetRunRequest\x1a\x1f.sentinelmesh.v1.GetRunResponse\x12R\n" +
	"\tCancelRun\x12!.sentinelmesh.v1.CancelRunRequest\x1a\".sentinelmesh.v1.CancelRunResponse\x12X\n" +
	"\vGetRunState\x12#.sentinelmesh.v1.GetRunStateRequest\x1a$.sentinelmesh.v1.GetRunStateResponseB-Z+github.com/sentinelmesh/sentinelmesh/api/v1b\x06proto3"

var (
	file_api_proto_sentinelmesh_proto_rawDescOnce sync.Once
	file_api_proto_sentinelmesh_proto_rawDescData []byte
)

func file_api_proto_sentinelmesh_proto_rawDescGZIP() []byte {
	file_api_proto_sentinelmesh_proto_rawDescOnce.Do(func() {
		file_api_proto_sentinelmesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_sentinelmesh_proto_rawDesc), len(file_api_proto_sentinelmesh_proto_rawDesc)))
	})
	return file_api_proto_sentinelmesh_proto_rawDescData
}

var file_api_proto_sentinelmesh_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_api_proto_sentinelmesh_proto_goTypes = []any{
	(*Resources)(nil),             // 0: sentinelmesh.v1.Resources
	(*CheckpointPolicy)(nil),      // 1: sentinelmesh.v1.CheckpointPolicy
	(*SecurityPolicy)(nil),        // 2: sentinelmesh.v1.SecurityPolicy
	(*NetworkPolicy)(nil),         // 3: sentinelmesh.v1.NetworkPolicy
	(*VerificationPolicy)(nil),    // 4: sentinelmesh.v1.VerificationPolicy
	(*Agent)(nil),                 // 5: sentinelmesh.v1.Agent
	(*AgentRun)(nil),              // 6: sentinelmesh.v1.AgentRun
	(*Checkpoint)(nil),            // 7: sentinelmesh.v1.Checkpoint
	(*Policy)(nil),                // 8: sentinelmesh.v1.Policy
	(*VerificationResult)(nil),    // 9: sentinelmesh.v1.VerificationResult
	(*CreateAgentRequest)(nil),    // 10: sentinelmesh.v1.CreateAgentRequest
	(*CreateAgentResponse)(nil),   // 11: sentinelmesh.v1.CreateAgentResponse
	(*GetAgentRequest)(nil),       // 12: sentinelmesh.v1.GetAgentRequest
	(*GetAgentResponse)(nil),      // 13: sentinelmesh.v1.GetAgentResponse
	(*ListAgentsRequest)(nil),     // 14: sentinelmesh.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),    // 15: sentinelmesh.v1.ListAgentsResponse
	(*DeleteAgentRequest)(nil),    // 16: sentinelmesh.v1.DeleteAgentRequest
	(*DeleteAgentResponse)(nil),   // 17: sentinelmesh.v1.DeleteAgentResponse
	(*CreateRunRequest)(nil),      // 18: sentinelmesh.v1.CreateRunRequest
	(*CreateRunResponse)(nil),     // 19: sentinelmesh.v1.CreateRunResponse
	(*GetRunRequest)(nil),         // 20: sentinelmesh.v1.GetRunRequest
	(*GetRunResponse)(nil),        // 21: sentinelmesh.v1.GetRunResponse
	(*CancelRunRequest)(nil),      // 22: sentinelmesh.v1.CancelRunRequest
	(*CancelRunResponse)(nil),     // 23: sentinelmesh.v1.CancelRunResponse
	(*GetRunStateRequest)(nil),    // 24: sentinelmesh.v1.GetRunStateRequest
	(*GetRunStateResponse)(nil),   // 25: sentinelmesh.v1.GetRunStateResponse
	(*timestamppb.Timestamp)(nil), // 26: google.protobuf.Timestamp
}
var file_api_proto_sentinelmesh_proto_depIdxs = []int32{
	0,  // 0: sentinelmesh.v1.Agent.resources:type_name -> sentinelmesh.v1.Resources
	2,  // 1: sentinelmesh.v1.Agent.security_policy:type_name -> sentinelmesh.v1.SecurityPolicy
	3,  // 2: sentinelmesh.v1.Agent.network_policy:type_name -> sentinelmesh.v1.NetworkPolicy
	1,  // 3: sentinelmesh.v1.Agent.checkpoint_policy:type_name -> sentinelmesh.v1.CheckpointPolicy
	4,  // 4: sentinelmesh.v1.Agent.verification_policy:type_name -> sentinelmesh.v1.VerificationPolicy
	26, // 5: sentinelmesh.v1.Agent.created_at:type_name -> google.protobuf.Timestamp
	26, // 6: sentinelmesh.v1.Agent.updated_at:type_name -> google.protobuf.Timestamp
	26, // 7: sentinelmesh.v1.AgentRun.started_at:type_name -> google.protobuf.Timestamp
	26, // 8: sentinelmesh.v1.AgentRun.finished_at:type_name -> google.protobuf.Timestamp
	26, // 9: sentinelmesh.v1.Checkpoint.created_at:type_name -> google.protobuf.Timestamp
	26, // 10: sentinelmesh.v1.VerificationResult.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 11: sentinelmesh.v1.CreateAgentRequest.resources:type_name -> sentinelmesh.v1.Resources
	5,  // 12: sentinelmesh.v1.CreateAgentResponse.agent:type_name -> sentinelmesh.v1.Agent
	5,  // 13: sentinelmesh.v1.GetAgentResponse.agent:type_name -> sentinelmesh.v1.Agent
	5,  // 14: sentinelmesh.v1.ListAgentsResponse.agents:type_name -> sentinelmesh.v1.Agent
	6,  // 15: sentinelmesh.v1.CreateRunResponse.run:type_name -> sentinelmesh.v1.AgentRun
	6,  // 16: sentinelmesh.v1.GetRunResponse.run:type_name -> sentinelmesh.v1.AgentRun
	6,  // 17: sentinelmesh.v1.CancelRunResponse.run:type_name -> sentinelmesh.v1.AgentRun
	10, // 18: sentinelmesh.v1.AgentService.CreateAgent:input_type -> sentinelmesh.v1.CreateAgentRequest
	12, // 19: sentinelmesh.v1.AgentService.GetAgent:input_type -> sentinelmesh.v1.GetAgentRequest
	14, // 20: sentinelmesh.v1.AgentService.ListAgents:input_type -> sentinelmesh.v1.ListAgentsRequest
	16, // 21: sentinelmesh.v1.AgentService.DeleteAgent:input_type -> sentinelmesh.v1.DeleteAgentRequest
	18, // 22: sentinelmesh.v1.RunService.CreateRun:input_type -> sentinelmesh.v1.CreateRunRequest
	20, // 23: sentinelmesh.v1.RunService.GetRun:input_type -> sentinelmesh.v1.GetRunRequest
	22, // 24: sentinelmesh.v1.RunService.CancelRun:input_type -> sentinelmesh.v1.CancelRunRequest
	24, // 25: sentinelmesh.v1.RunService.GetRunState:input_type -> sentinelmesh.v1.GetRunStateRequest
	11, // 26: sentinelmesh.v1.AgentService.CreateAgent:output_type -> sentinelmesh.v1.CreateAgentResponse
	13, // 27: sentinelmesh.v1.AgentService.GetAgent:output_type -> sentinelmesh.v1.GetAgentResponse
	15, // 28: sentinelmesh.v1.AgentService.ListAgents:output_type -> sentinelmesh.v1.ListAgentsResponse
	17, // 29: sentinelmesh.v1.AgentService.DeleteAgent:output_type -> sentinelmesh.v1.DeleteAgentResponse
	19, // 30: sentinelmesh.v1.RunService.CreateRun:output_type -> sentinelmesh.v1.CreateRunResponse
	21, // 31: sentinelmesh.v1.RunService.GetRun:output_type -> sentinelmesh.v1.GetRunResponse
	23, // 32: sentinelmesh.v1.RunService.CancelRun:output_type -> sentinelmesh.v1.CancelRunResponse
	25, // 33: sentinelmesh.v1.RunService.GetRunState:output_type -> sentinelmesh.v1.GetRunStateResponse
	26, // [26:34] is the sub-list for method output_type
	18, // [18:26] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_api_proto_sentinelmesh_proto_init() }
func file_api_proto_sentinelmesh_proto_init() {
	if File_api_proto_sentinelmesh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_sentinelmesh_proto_rawDesc), len(file_api_proto_sentinelmesh_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_proto_sentinelmesh_proto_goTypes,
		DependencyIndexes: file_api_proto_sentinelmesh_proto_depIdxs,
		MessageInfos:      file_api_proto_sentinelmesh_proto_msgTypes,
	}.Build()
	File_api_proto_sentinelmesh_proto = out.File
	file_api_proto_sentinelmesh_proto_goTypes = nil
	file_api_proto_sentinelmesh_proto_depIdxs = nil
}
