apiVersion: v1
kind: ServiceAccount
metadata:
  name: sentinelmesh-operator
  namespace: sentinelmesh
  labels:
    app.kubernetes.io/name: sentinelmesh-operator
    app.kubernetes.io/component: operator
